name: Tests

on:
  push:
    branches:
      - main
      - "!dependabot/**"
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 20

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
        with:
          node-version: "${{ env.NODE }}"
          cache: npm

      - run: java -version

      - name: Install npm dependencies
        run: npm ci

      - name: Build the icons
        run: npm run icons

      - name: Build and test docs
        run: npm run docs-test

      - name: Run linkinator
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: _site
          recurse: true
          verbosity: error
          skip: "^(?!http://localhost)"
